#
# This site was originally deployed by Netlify to https://jsb.christmind.info. This has changed
# so that it is incorporated into the Netlify site cmi-www and is accessed at
# https://www.christmind.info/t/jsb.
#
# This config file is used update the cmi-acol Netlify site with a page that imforms the user
# that the site has moved and to include a _redirects file that will forward references to 
# https://jsb.christmind.info to the appropriate destination.
#
# To develop this site
#
# 1. npm run deploy:netlify
# 2. Edit moved.md, _redirects and any other files
# 3. Test locally at localhost:9912
# 4. Use the command line from the project root to deploy to Netlify
#     $ netlify deploy --prod
#
# The switch from https://jsb.christmind.info to https://www.christmind.info/t/jsb happened
# on March 19, 2019. Maintaining the old Netlify site, cmi-jsb, is needed only for a short 
# time.
#
# CMI
sourceId: 11
cmiTitle: "Teachings of Christ Mind"
sid: "jsb"

# Setup
title:        'The Impersonal Life'
tagline:      ''
description:  'The Impersonal Life by Joseph S. Benner 1914'
url:          'https://jsb.christmind.info/'
baseurl:      ''
keywords:     "Christ Mind, spiritual, The Impersonal Life, Joseph S. Benner"
port:         9911

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107
src-url:      'https://jsb.christmind.info'

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown

include: [ _redirects ]

exclude: [
  deploy,
  LICENSE,
  README.md,
  Gemfile,
  Gemfile.lock,
  package.json,
  package-lock.json,
  node_modules,
  webpack.config.js,
  src,
  project,
  _acq,
  _til
]

